# Generated by Django 5.1.3 on 2024-12-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FemBloomApp', '0003_question_quiz_option_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
    ]
