# Generated by Django 5.1.3 on 2024-12-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FemBloomApp', '0005_signin_rename_user_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='name',
            new_name='Fullname',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='password',
            new_name='Password',
        ),
    ]
