# Generated by Django 5.1.3 on 2024-12-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FemBloomApp', '0007_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FemBloomApp.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FemBloomApp.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FemBloomApp.signup')),
            ],
        ),
    ]
