# Generated by Django 5.1.3 on 2024-12-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FemBloomApp', '0009_institution_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='type',
        ),
    ]
