# Generated by Django 5.1.3 on 2024-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FemBloomApp', '0010_remove_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
