# Generated by Django 5.1.3 on 2024-12-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FemBloomApp', '0012_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('sponsor_email', models.EmailField(max_length=200)),
                ('donation_amount', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
